version: '3.8'
services:
  cosmos-db:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    container_name: cosmos-db
    restart: always
    ports:
      - "8081:8081"
      - "8900:8900"
    environment:
      AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 10
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: "true"
    tty: true
    stdin_open: true
    volumes:
      - data:/data/db
      - data:/var/lib/cosmosdb
    networks:
      db-net:
        ipv4_address: 172.16.238.246
  jet-set-go-be:
    image: ${DOCKER_REGISTRY-}jet-set-go-be
    container_name: jet-set-go-api
    build: backend
    restart: on-failure
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - cosmos-db
    networks:
      - jet-set-go-network
      - db-net
  jet-set-go-fe:
    image: ${DOCKER_REGISTRY-}jet-set-go-fe
    container_name: jet-set-go-fe
    build: frontend
    restart: on-failure
    ports:
      - "4200:80"
    networks:
      - jet-set-go-network
networks:
  jet-set-go-network:
    driver: bridge
  db-net:
    external: false
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
volumes:
  data:  
  