version: '3.8'
services:
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    container_name: cosmos-local
    restart: always
    ports:
      - "8081:8081"
      - "8900:8900"
    environment:
      AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 10
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: "true"
    tty: true
    stdin_open: true
    volumes:
      - data:/data/db
      - data:/var/lib/cosmosdb
    networks:
      default:
        ipv4_address: 172.16.238.246
volumes:
  data:
networks:
  default:
    external: false
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"